//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Cultures.Cultures {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Cultures.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호&amp;#10;   변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유저 아이디 입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnterUserID {
            get {
                return ResourceManager.GetString("EnterUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유저 패스워드 입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnterUserPassword {
            get {
                return ResourceManager.GetString("EnterUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   폴더찾기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디 기억과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IsLoginStatus {
            get {
                return ResourceManager.GetString("IsLoginStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인 중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LoginToYourAccount {
            get {
                return ResourceManager.GetString("LoginToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Plant {
            get {
                return ResourceManager.GetString("Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ProgramEnd {
            get {
                return ResourceManager.GetString("ProgramEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램을 종료 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ProgramEndQ {
            get {
                return ResourceManager.GetString("ProgramEndQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ProgramInfo {
            get {
                return ResourceManager.GetString("ProgramInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램 버전과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ProgramVersion {
            get {
                return ResourceManager.GetString("ProgramVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주요메뉴과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolHeader_MainMenu {
            get {
                return ResourceManager.GetString("ToolHeader_MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   툴바과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolHeader_ToolBar {
            get {
                return ResourceManager.GetString("ToolHeader_ToolBar", resourceCulture);
            }
        }
    }
}
